/// A country for the payment address. [code] is its ISO 3166-1 alpha-2
/// code, which also gives the flag.
class Country {
  const Country(this.code, this.name);

  final String code;
  final String name;

  /// Flag emoji built from the two regional indicator letters of [code].
  String get flag =>
      String.fromCharCodes(code.codeUnits.map((c) => 0x1F1E6 + c - 0x41));

  /// States to pick from, or null to type the state in.
  List<String>? get states => _states[code];

  static const india = Country('IN', 'India');

  static const all = [
    Country('AF', 'Afghanistan'),
    Country('AL', 'Albania'),
    Country('DZ', 'Algeria'),
    Country('AD', 'Andorra'),
    Country('AO', 'Angola'),
    Country('AG', 'Antigua and Barbuda'),
    Country('AR', 'Argentina'),
    Country('AM', 'Armenia'),
    Country('AU', 'Australia'),
    Country('AT', 'Austria'),
    Country('AZ', 'Azerbaijan'),
    Country('BS', 'Bahamas'),
    Country('BH', 'Bahrain'),
    Country('BD', 'Bangladesh'),
    Country('BB', 'Barbados'),
    Country('BY', 'Belarus'),
    Country('BE', 'Belgium'),
    Country('BZ', 'Belize'),
    Country('BJ', 'Benin'),
    Country('BT', 'Bhutan'),
    Country('BO', 'Bolivia'),
    Country('BA', 'Bosnia and Herzegovina'),
    Country('BW', 'Botswana'),
    Country('BR', 'Brazil'),
    Country('BN', 'Brunei'),
    Country('BG', 'Bulgaria'),
    Country('BF', 'Burkina Faso'),
    Country('BI', 'Burundi'),
    Country('CV', 'Cabo Verde'),
    Country('KH', 'Cambodia'),
    Country('CM', 'Cameroon'),
    Country('CA', 'Canada'),
    Country('CF', 'Central African Republic'),
    Country('TD', 'Chad'),
    Country('CL', 'Chile'),
    Country('CN', 'China'),
    Country('CO', 'Colombia'),
    Country('KM', 'Comoros'),
    Country('CG', 'Congo'),
    Country('CD', 'Congo (DRC)'),
    Country('CR', 'Costa Rica'),
    Country('CI', 'Côte d\'Ivoire'),
    Country('HR', 'Croatia'),
    Country('CU', 'Cuba'),
    Country('CY', 'Cyprus'),
    Country('CZ', 'Czechia'),
    Country('DK', 'Denmark'),
    Country('DJ', 'Djibouti'),
    Country('DM', 'Dominica'),
    Country('DO', 'Dominican Republic'),
    Country('EC', 'Ecuador'),
    Country('EG', 'Egypt'),
    Country('SV', 'El Salvador'),
    Country('GQ', 'Equatorial Guinea'),
    Country('ER', 'Eritrea'),
    Country('EE', 'Estonia'),
    Country('SZ', 'Eswatini'),
    Country('ET', 'Ethiopia'),
    Country('FJ', 'Fiji'),
    Country('FI', 'Finland'),
    Country('FR', 'France'),
    Country('GA', 'Gabon'),
    Country('GM', 'Gambia'),
    Country('GE', 'Georgia'),
    Country('DE', 'Germany'),
    Country('GH', 'Ghana'),
    Country('GR', 'Greece'),
    Country('GD', 'Grenada'),
    Country('GT', 'Guatemala'),
    Country('GN', 'Guinea'),
    Country('GW', 'Guinea-Bissau'),
    Country('GY', 'Guyana'),
    Country('HT', 'Haiti'),
    Country('HN', 'Honduras'),
    Country('HK', 'Hong Kong'),
    Country('HU', 'Hungary'),
    Country('IS', 'Iceland'),
    Country('IN', 'India'),
    Country('ID', 'Indonesia'),
    Country('IR', 'Iran'),
    Country('IQ', 'Iraq'),
    Country('IE', 'Ireland'),
    Country('IL', 'Israel'),
    Country('IT', 'Italy'),
    Country('JM', 'Jamaica'),
    Country('JP', 'Japan'),
    Country('JO', 'Jordan'),
    Country('KZ', 'Kazakhstan'),
    Country('KE', 'Kenya'),
    Country('KI', 'Kiribati'),
    Country('KW', 'Kuwait'),
    Country('KG', 'Kyrgyzstan'),
    Country('LA', 'Laos'),
    Country('LV', 'Latvia'),
    Country('LB', 'Lebanon'),
    Country('LS', 'Lesotho'),
    Country('LR', 'Liberia'),
    Country('LY', 'Libya'),
    Country('LI', 'Liechtenstein'),
    Country('LT', 'Lithuania'),
    Country('LU', 'Luxembourg'),
    Country('MO', 'Macao'),
    Country('MG', 'Madagascar'),
    Country('MW', 'Malawi'),
    Country('MY', 'Malaysia'),
    Country('MV', 'Maldives'),
    Country('ML', 'Mali'),
    Country('MT', 'Malta'),
    Country('MH', 'Marshall Islands'),
    Country('MR', 'Mauritania'),
    Country('MU', 'Mauritius'),
    Country('MX', 'Mexico'),
    Country('FM', 'Micronesia'),
    Country('MD', 'Moldova'),
    Country('MC', 'Monaco'),
    Country('MN', 'Mongolia'),
    Country('ME', 'Montenegro'),
    Country('MA', 'Morocco'),
    Country('MZ', 'Mozambique'),
    Country('MM', 'Myanmar'),
    Country('NA', 'Namibia'),
    Country('NR', 'Nauru'),
    Country('NP', 'Nepal'),
    Country('NL', 'Netherlands'),
    Country('NZ', 'New Zealand'),
    Country('NI', 'Nicaragua'),
    Country('NE', 'Niger'),
    Country('NG', 'Nigeria'),
    Country('KP', 'North Korea'),
    Country('MK', 'North Macedonia'),
    Country('NO', 'Norway'),
    Country('OM', 'Oman'),
    Country('PK', 'Pakistan'),
    Country('PW', 'Palau'),
    Country('PS', 'Palestine'),
    Country('PA', 'Panama'),
    Country('PG', 'Papua New Guinea'),
    Country('PY', 'Paraguay'),
    Country('PE', 'Peru'),
    Country('PH', 'Philippines'),
    Country('PL', 'Poland'),
    Country('PT', 'Portugal'),
    Country('PR', 'Puerto Rico'),
    Country('QA', 'Qatar'),
    Country('RO', 'Romania'),
    Country('RU', 'Russia'),
    Country('RW', 'Rwanda'),
    Country('KN', 'Saint Kitts and Nevis'),
    Country('LC', 'Saint Lucia'),
    Country('VC', 'Saint Vincent and the Grenadines'),
    Country('WS', 'Samoa'),
    Country('SM', 'San Marino'),
    Country('ST', 'São Tomé and Príncipe'),
    Country('SA', 'Saudi Arabia'),
    Country('SN', 'Senegal'),
    Country('RS', 'Serbia'),
    Country('SC', 'Seychelles'),
    Country('SL', 'Sierra Leone'),
    Country('SG', 'Singapore'),
    Country('SK', 'Slovakia'),
    Country('SI', 'Slovenia'),
    Country('SB', 'Solomon Islands'),
    Country('SO', 'Somalia'),
    Country('ZA', 'South Africa'),
    Country('KR', 'South Korea'),
    Country('SS', 'South Sudan'),
    Country('ES', 'Spain'),
    Country('LK', 'Sri Lanka'),
    Country('SD', 'Sudan'),
    Country('SR', 'Suriname'),
    Country('SE', 'Sweden'),
    Country('CH', 'Switzerland'),
    Country('SY', 'Syria'),
    Country('TW', 'Taiwan'),
    Country('TJ', 'Tajikistan'),
    Country('TZ', 'Tanzania'),
    Country('TH', 'Thailand'),
    Country('TL', 'Timor-Leste'),
    Country('TG', 'Togo'),
    Country('TO', 'Tonga'),
    Country('TT', 'Trinidad and Tobago'),
    Country('TN', 'Tunisia'),
    Country('TR', 'Türkiye'),
    Country('TM', 'Turkmenistan'),
    Country('TV', 'Tuvalu'),
    Country('UG', 'Uganda'),
    Country('UA', 'Ukraine'),
    Country('AE', 'United Arab Emirates'),
    Country('GB', 'United Kingdom'),
    Country('US', 'United States'),
    Country('UY', 'Uruguay'),
    Country('UZ', 'Uzbekistan'),
    Country('VU', 'Vanuatu'),
    Country('VA', 'Vatican City'),
    Country('VE', 'Venezuela'),
    Country('VN', 'Vietnam'),
    Country('YE', 'Yemen'),
    Country('ZM', 'Zambia'),
    Country('ZW', 'Zimbabwe'),
  ];

  static const _states = {
    'IN': [
      'Andaman and Nicobar Islands',
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chandigarh',
      'Chhattisgarh',
      'Dadra and Nagar Haveli and Daman and Diu',
      'Delhi',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Ladakh',
      'Lakshadweep',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Puducherry',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
    ],
    'US': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'District of Columbia',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  };

  @override
  bool operator ==(Object other) => other is Country && other.code == code;

  @override
  int get hashCode => code.hashCode;
}
